
spring:
   application:
     name: eureka-consumer
server:
  port: 8702

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8697/eureka,http://${eureka.instance.hostname}:8698/eureka,http://${eureka.instance.hostname}:8699/eureka
  instance:
    hostname: localhost